apiVersion: v1
kind: Service
metadata:
  name: service-database
spec:
  selector:
    app: database-pod
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-deployment
  labels:
    app: database
spec:
  serviceName: database
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: database-pod
  template:
    metadata:
      labels:
        app: database-pod
    spec:
      restartPolicy: Always
      containers:
      - name: database-cont
        image: bart120/yv-database:1
        resources:
           limits:
             cpu: 2000m
             memory: 1000Mi
           requests:
             cpu: 100m
             memory: 200Mi
        ports:
        - containerPort: 1433
        volumeMounts:
          - name: database-persistent-storage
            mountPath: /var/lib/database
  volumeClaimTemplates:
  - metadata:
      name: database-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi