apiVersion: v1
kind: Service
metadata:
  name: service-user-data
spec:
  selector:
    app: user-data
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-data-deployment
  labels:
    app: user-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-data-pod
  template:
    metadata:
      labels:
        app: user-data-pod
    spec:
      restartPolicy: Always
      containers:
      - name: user-data-cont
        image: redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 500m