apiVersion: v1
kind: Service
metadata:
  name: service-api-jobs
spec:
  selector:
    app: api-jobs-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-jobs-deployment
  labels:
    app: api-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-jobs-pod
  template:
    metadata:
      labels:
        app: api-jobs-pod
    spec:
      containers:
      - name: api-jobs-cont
        image: bart120/yv-api-jobs:2
        resources:
           limits:
             cpu: 1000m
             memory: 1000Mi
           requests:
             cpu: 100m
             memory: 200Mi
        env:
        - name: ConnectionString
          value: "Server=service-database;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;"
        - name: HostRabbitmq
          value: "service-rabittmq"
        ports:
        - containerPort: 80